### ISSUE TITLE
Unknown error at runtime

### ISSUE THREAD

**Issue by tux3** [novomesk/qt-avif-image-plugin#2]
Hello, I successfully compiled and installed the plugin, however I get errors when opening avif images (encoded with the latest libaom/libavif):

```
$ gwenview file.avif
QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 20102 in a call to canRead()! Rewinding.
QImageReader::read() without format hint failed: "Unsupported image format"
QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 50421 in a call to canRead()! Rewinding.
QImageReader::read() without format hint failed: "Unsupported image format"
```

I've tried both the static and dynamic build, but I get the same result.

**Comment by novomesk** [comment]
Hello,
thanks for the message.
Right now I don't know where is the problem, I need more information.

1) Can you test the official testfiles? https://github.com/AOMediaCodec/av1-avif/tree/master/testFiles

2) Can you attach your file.avif file?

3) What is the distribution you are using? (So I can try to reproduce the problem)

4) What is the version of your Qt and compiler?
`qmake -v`
`gcc --version`

**Comment by tux3** [comment]
1. None of those show as thumbnail in dolphin, I have tried opening a few of them:

<details>
  <summary>gwenview testFiles/Link-U/fox.profile0.8bpc.yuv420.avif</summary>

```            
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 63479 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
ERROR: Failed to parse input: Decoding of color planes failed

discarding "Send SMS via KDE Connect" ("ShareUrl")
kf5.kio.core: "Could not enter folder tags:/."
kf5.kio.core: "Could not enter folder tags:/."
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 55649 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
```
</details>

<details>
  <summary>gwenview testFiles/Microsoft/Mexico_YUV444.avif</summary>

```
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 158840 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
ERROR: Failed to parse input: Decoding of color planes failed

discarding "Send SMS via KDE Connect" ("ShareUrl")
kf5.kio.core: "Could not enter folder tags:/."
kf5.kio.core: "Could not enter folder tags:/."
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 219216 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
```
</details>

<details>
  <summary>gwenview testFiles/Netflix/avif/cosmos_frame12924_yuv420_8bpc_bt709_g22_q80.avif</summary>

```
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 235097 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
ERROR: Failed to parse input: Decoding of color planes failed

discarding "Send SMS via KDE Connect" ("ShareUrl")
kf5.kio.core: "Could not enter folder tags:/."
kf5.kio.core: "Could not enter folder tags:/."
ERROR: Failed to parse input: Decoding of color planes failed

QImageReader::read() using format hint "avif" failed: "Unknown error"
A bad Qt image decoder moved the buffer to 1009404 in a call to canRead()! Rewinding.
Image format is actually "avif" not "avif"
```
</details>

2. I can also reproduce with all the official testfiles, but please see the file names I tested above

3. Debian GNU/Linux bullseye/sid, using NVidia proprietary drivers

4.
```
QMake version 3.1
Using Qt version 5.12.5 in /usr/lib/x86_64-linux-gnu
```

```
gcc (Debian 9.3.0-10) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by novomesk** [comment]
I am unable to download your fox.avif, but aomenc is not producing files in AVIF format.
Correct utility is **avifenc** from libavif  package or good convertor is https://github.com/joedrago/colorist .
So this part is explained but why the official files did not work for you is a subject for further investigation.
Result of `gwenview fox.profile0.8bpc.yuv420.avif` on my computer is:
![foxtest](https://user-images.githubusercontent.com/52529860/79076850-67e74000-7cfd-11ea-88d1-e158a83d1092.png)

I see the error "**ERROR: Failed to parse input: Decoding of color planes failed**" - this is printed by me. It may indicate problem with libaom (for example when you upgrade libaom without rebuilding libavif). I see you list dynamic version of libqavif.so
Try to temporarily remove libavif installed in your system (including avif/avif.h avif/internal.h headers), build again the static libqavif.so , put it to /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/ and try again the official test files.

Let me know when you have some news.

BTW, if you type `avifenc -h` it will tell you version of AV1 encoders and decoders. For example:
`Version: 0.6.3 (dav1d:0.5.2, aom:1.0.0-errata1-avif-524-gd25c09124)`
It would be good to know the version of the libaom snapshot.

**Comment by tux3** [comment]
Okay, I tried the static build again and it does work with the official test files.

I see now that aomenc actually made a .webm with the .avif extension... won't be making that mistake again.
I was also getting segfaults with aom & avifenc master (Version: 0.6.3 (aom:1.0.0-2499-gce7d07ee6)) when encoding anything, but actually it seems I had an old libaom.so lying around (and aom only builds the static lib by default!).

Everything seems to be working now! =]
Thank you!

**Comment by tux3** [comment]
Hhhm now I get crashes in all kinds of KDE programs, but I don't know if I did something wrong this time :/

```
Thread 1 (Thread 0x7efcd047a340 (LWP 1347)):
[KCrash Handler]
#6  0x00007efcd6c95598 in QMetaObject::cast(QObject const*) const () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007efcd70d8f86 in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#8  0x00007efcd70da02c in  () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#9  0x00007efcd70dab9c in QImageReader::canRead() const () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#10 0x00007efcd3c0e3b4 in  () at /usr/lib/x86_64-linux-gnu/libKF5IconThemes.so.5
#11 0x00007efcd3c0ee8d in KIconLoader::loadScaledIcon(QString const&, KIconLoader::Group, double, int, int, QStringList const&, QString*, bool) const () at /usr/lib/x86_64-linux-gnu/libKF5IconThemes.so.5
#12 0x00007efcd3c0374c in KIconEngine::createPixmap(QSize const&, double, QIcon::Mode, QIcon::State) () at /usr/lib/x86_64-linux-gnu/libKF5IconThemes.so.5
#13 0x00007efcd3c039a6 in KIconEngine::pixmap(QSize const&, QIcon::Mode, QIcon::State) () at /usr/lib/x86_64-linux-gnu/libKF5IconThemes.so.5
#14 0x00007efcd70fe18b in QIcon::pixmap(QWindow*, QSize const&, QIcon::Mode, QIcon::State) const () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#15 0x00007efcd70fe2af in QIcon::pixmap(QSize const&, QIcon::Mode, QIcon::State) const () at /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007efccc10db22 in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so
#17 0x00007efcd7bdc725 in KWindowSystem::icon(unsigned long long, int, int, bool, int, NETWinInfo*) () at /usr/lib/x86_64-linux-gnu/libKF5WindowSystem.so.5
#18 0x00007efcd7e9138c in KWin::Client::getIcons() () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#19 0x00007efcd7f43f8d in KWin::Client::manage(unsigned int, bool) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#20 0x00007efcd7ff0fd5 in KWin::Workspace::createClient(unsigned int, bool) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#21 0x00007efcd7eeed2f in KWin::Workspace::workspaceEvent(xcb_generic_event_t*) () at /usr/lib/x86_64-linux-gnu/libkwin.so.5
#22 0x00007efcd6c8a037 in QAbstractEventDispatcher::filterNativeEvent(QByteArray const&, void*, long*) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007efccffab921 in QXcbConnection::handleXcbEvent(xcb_generic_event_t*) () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#24 0x00007efccffac8ca in QXcbConnection::processXcbEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#25 0x00007efccffd706c in  () at /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#26 0x00007efcd6c8b6db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007efcd6c93182 in QCoreApplication::exec() () at /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007efcd82b0b24 in kdemain () at /usr/lib/x86_64-linux-gnu/libkdeinit5_kwin_x11.so
#29 0x00007efcd810ae0b in __libc_start_main (main=0x557e277aa050, argc=3, argv=0x7ffc3e5dd908, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffc3e5dd8f8) at ../csu/libc-start.c:308
#30 0x0000557e277aa08a in _start ()
[Inferior 1 (process 1347) detached]
```

**Comment by novomesk** [comment]
The crash is expected when you overwrite the plug-in with the new version. This is a one-time issue.
I experienced it too, when I was updating the plug-in frequently. When I delete the old version first before copying the the new one, I often avoid crashes.

Old libaom cannot be used with AVIF, we need https://aomedia.googlesource.com/aom/+/refs/tags/v1.0.0-errata1-avif or newer.
